###
http://localhost:1234/users/1112
###
POST http://localhost:1234/users
Content-Type:application/json

{
    "id":"1112",
    "name" : "tahoad chaisri",
    "email" : "tahoad@gmail.com"
}
###
PUT http://localhost:1234/users/12345
Content-Type: : application/json

{
    
}
###
POST http://localhost:1234/registEmp
Content-Type:application/json

{
    "id":"1112",
    "username":"tahoad",
    "password":"12345",
    "email" : "tahoad@gmail.com",
    "name" : "tahoad",
    "surname":"chaisri"
}